name: Build
on: [push]
jobs:
  build-step:
    runs-on: ubuntu-latest
    env:
      GIT_DATABASE: ${{ secrets.DATABASE_KEY }}
      GIT_SPOTIFY: ${{ secrets.SPOTIFY_KEY }}
      GIT_OPENAI: ${{ secrets.OPENAI_API_KEY }}
      GIT_IP: ${{ secrets.IP_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install flask
        run: pip install flask
      - name: Install all
        run: pip install -r api/requirements.txt
      - name: Install pytest
        run: pip install pytest
      - name: Install bs4
        run: pip install bs4
      - name: Install requests
        run: pip install requests
      - name: Run unit tests
        run: pytest api/app_test.py
      - name: Run spotify tests
        run: pytest api/spotify_test.py
  database-connection:
    runs-on: ubuntu-latest
    env:
      GIT_DATABASE: ${{ secrets.DATABASE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install all
        run: pip install -r api/requirements.txt
      - name: Run database tests
        run: pytest api/database_test.py
  browser-tests:
    needs: build-step
    needs: database-connection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install pytest
        run: pip install pytest
      - name: Install bs4
        run: pip install bs4
      - name: Install requests
        run: pip install requests
      - name: Run browser tests
        run: pytest api/browser_test.py
  deploy-to-vercel:
    needs: browser-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'